export const GET_ERRORS = "GET_ERRORS";
export const RECEIVE_HISTORY = "RECEIVE_HISTORY";
export const REQUEST_HISTORY = "REQUEST_HISTORY";
export const RECEIVE_PROJECT = "RECEIVE_PROJECT";
export const REQUEST_PROJECT = "REQUEST_PROJECT";
